### ISSUE TITLE
Note background too dark in light mode

### ISSUE THREAD

**Issue by annadrg** [mkosir/typescript-style-guide#8]
### Description

The background color of a note doesn't change between dark/light mode, causing it to be hard to read in light mode.
<img width="665" alt="Scherm­afbeelding 2024-01-31 om 12 19 06" src="https://github.com/mkosir/typescript-style-guide/assets/54747347/9a5403c9-ee77-457f-b53a-f565c4ae5c9c">

**Comment by mkosir** [comment]
Hi @annadrg , thanks for catching it!
Would you like to take a stab at this and create PR?

**Comment by annadrg** [comment]
Sure, I will take a look at it when I have some time!

**Comment by mkosir** [comment]
Thanks for the PR 🚀
